### PR TITLE
Add support for exporting images with a custom background color.

### PR DESCRIPTION
**Pull request by kaphula**
Adds support for specifying custom background color for the exported images.

### CODE REVIEW

**Comment by kaphula** [comment]
While it kinda works, I noticed that if you have regions with transparent regions, they will not match the set background color.

**Comment by kaphula** [comment]
I added separate options for dealing with issue of what happens you set a background color but your image regions' pixels contain transparent pixels. You can now override the region's transparent pixels with the background color when certain threshold for alpha is reached. 

Further more, if the threshold test fails, you can optionally set the image region pixels to not have transparency at all (sets alpha to 255). This option helps in cases where your region pixels have alpha values somewhere in between 0-255 but you want the end result exported image to not have any transparency anywhere. This could be expanded to allow user to decide if color from the region pixel should be used or just the specified background color.

**Comment by bvssvni** [comment]
Merging.

**Comment by bvssvni** [comment]
Thanks!

**Comment by kaphula** [comment]
Thanks. If you have any ideas for improvements regarding this I am possibly open for implementing them at some point.

**Pull request merged**
