### PR TITLE
Removed the local Cow implementation and updated to std::borrow::Cow

### PR DESCRIPTION
**Pull request by Esption**
As requested by https://github.com/PistonDevelopers/texture_packer/issues/26

### CODE REVIEW

**Comment by Esption** [comment]
Ah, seems that wasn't enough.  Need to add #[derive(Clone)] to some other things too.  Didn't realise I'd need to test the example too.  Will see what I can do. Though, one of the issues will be adding a Clone derive to DynamicImage in PistonDevelopers/image

**Comment by bvssvni** [comment]
@Esption You can commit multiple times and it will be added to the same PR.

**Comment by Esption** [comment]
Okay, thanks.  Figured I'd learn how to use github by doing some random things in Piston. Hope I'm not a bother too much.

**Comment by bvssvni** [comment]
@Esption No problem. Reopened.

**Comment by Esption** [comment]
Okay, it seems to build fine with #[derive(Clone)] being on DynamicImage.  No actual changes needed for this PR. Just need to accept https://github.com/PistonDevelopers/image/pull/404 and then this PR (should) compile fine.

**Comment by bvssvni** [comment]
Nice!

**Pull request merged**
