### PR TITLE
MultiTexturePacker and migration to 2018 edition, bug fixes

### PR DESCRIPTION
**Pull request by PsichiX**
- packing returns error on fail instead of throwing assert;
- migration to 2018 edition;
- added multi texture packer to generate multiple atlases

### CODE REVIEW

**Comment by PsichiX** [comment]
github tips told me to ping you @bvssvni to make review happen :)

**Comment by bvssvni** [comment]
Looks good!

**Comment by bvssvni** [comment]
Merging.

**Comment by bvssvni** [comment]
Thanks!

**Pull request merged**
